spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: swift
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.cn.lp.entity